return {
    descriptions = {
        Mod = {
            PlayLog = {
                name = "PlayLog",
                text = {
                    "Adds a log to the game",
                    " ",
                    "Icon by {C:attention}J8-Bit"
                }
            }
        },
    },
    misc = {
        playlog_ui = {
            header = "PLAY LOG",
            select_theme = "SELECT THEME",
            time_format = "TIME FORMAT",
            log_opacity = "LOG OPACITY",
            log_types = "LOG TYPES",
            open_log_type_selection = "Open selector",
            custom_colours = "CUSTOM COLORS  (click swatch to open picker)",
            colour_panel_bg = "Background",
            colour_border = 'Border / Accent',
            colour_header_text = 'Text',
            copy = "CPY",
            copy_ok = "OK",
            copied = "COPIED",
            log_button = "LOG",
            config_button = "CFG",
            back_button = "BACK",
            editing_colour = "EDITING: ",
            edit_hex = "click to type hex"
        },
        playlog_themes = {
            Gold = "Gold",
            Purple = "Purple",
            Green = "Green",
            Red = "Red",
            Blue = "Blue",
            Mono = "Mono"
        },
        playlog_types = {
            hand_played = "Hand Played",
            added_blind_size = "Blind Size changed",
            added_score = "Total score changed",
            blueprint = "Ability copied",
            score = "Card scored",
            defeated_blind = "Blind Defeated",
            buy = "Card bought",
            changed_sell_cost = "Sell value changed",
            copies = "Card copied",
            scale = "Card changed values",
            eaten = "Food expired",
            perished = "Card perished",
            started = "Run started",
            selected_blind = "Blind selected",
            booster_skipped = "Booster skipped",
            starting_shop = "Shop started",
            booster_opened = "Booster opened",
            use = "Card used",
            perishable = "Perishable count",
            discarded = "Cards discarded",
            start_ante = "Ante changed",
            creates = "Card created",
            added = "Card added to deck/slots",
            reroll_shop = "Shop rerolled",
            money_altered = "Money changed",
            start_round = "Round started",
            selected_card = "Card was selected by an ability",
            sell = "Card sold",
            cash_out = "Cashed out",
            converts_multiple = "Multiple cards modified",
            reroll_shop_into = "Shop cards rerolled into",
            hand_played_as = "Poker Hand played changed",
            blind_disabled = "Blind disabled",
            area_size = "Area size changed",
            target_changed = "Target card changed",
            options = "Custom starting run options",
            score_to_beat = "Score to beat",
            hand_drawn = "Hand drawn",
            tag_applied = "Tag applied",
            reroll_boss = "Boss rerolled",
            win = "Run won",
            change_area_size = "Card changed area size",
            resume = "Run resumed",
            hand_scored = "Hand scored",
            applied = "Card modified (Edition, Seal, Sticker)",
            ending_shop = "Shop ending",
            debuffed_hand = "Hand debuffed",
            saved = "Game Over prevented",
            destroys = "Card destroyed",
            reset = "Card values reset",
            hand_level_up = "Hand leveled up",
            added_to_shop = "Card added to shop",
            leveled_up = "Card leveled up hand",
            money = "Card modified money",
            message = "Generic log",
            lost = "Run lost",
            swap = "Scored swapped",
            balance = "Scored balanced",
            rental = "Rental rent paid",
            removed_modifier = "Removed modifier",
            converts = "Card modified (Enhancement, Rank, Suit)",
            skip_blind = "Blind Skipped",
            noped = "Card noped",
            leveled_down = "Hand leveled down",
        },
        playlog_groups = {
            generic = "Generic Logs",
            player_actions = "Player Actions",
            effects = "Effects",
            gamestate = "Gamestate",
            scoring = "Scoring"
        },
        playlog = {
            -- Formatting
            separator = "#1#, #2#",
            end_separator = "#1# and #2#",
            rank_of_suit = "#1# of #2#",
            playing_card = "Playing Card",

            -- Areas
            joker_area = "joker slots",
            consumable_area = "consumable slots",
            hand_area = "hand",
            deck_area = "deck",
            shop_jokers_area = "shop",
            shop_vouchers_area = "voucher shop",
            shop_boosters_area = "booster shop",

            -- Others
            all_hands = "all hands",
            mult = "#1#{} Mult", -- the {} is there as a dirty hack to finish the color formatting :3
            chips = "#1#{} Chips",

            -- Logging
            started = "Started game on #1#",
            started_challenge = "Started {C:attention}#1#{} challenge on #2#",
            resumed = "Resumed game",
            mod_options = "{C:attention}#1#{}: #2# enabled",
            selected_blind = "Selected #1#",
            defeated_blind = "Defeated #1#",
            blind_disabled = "#1# disabled",
            skip_blind = "Skipped #1#",
            skip_blind_for = "Skipped #1# for #2#",
            start_round = "Started {C:attention}round #1#{}",
            start_ante = "Started {C:attention}Ante #1#{}",
            ante_modified = "{C:attention}Ante{} changed {C:red}#1#{} -> {C:red}#2#{}",
            cash_out = "{C:money}$#1#{} cash out",
            creates = "{C:attention}#1#{} created #2#",
            destroys = "{C:attention}#1#{} destroyed #2#",
            used = "{C:attention}#1#{} used",
            starting_shop = "Started {C:attention}shop{}\nShop contains: #1#",
            ending_shop = "Ended {C:attention}shop{}",
            reroll_shop = "Rerolled {C:attention}shop{} for {C:money}$#1#{} to #2#",
            reroll_shop_into = "Rerolled into: #1#",
            added = "{C:attention}#1#{} added",
            added_to = "{C:attention}#1#{} added to {C:attention}#2#",
            added_to_shop = "{C:attention}#1#{} added {C:attention}#2#{} to the {C:attention}shop{}",
            converts = "{C:attention}#1#{} turned #2# into {C:attention}#3#",
            converts_multiple = "{C:attention}#1#{} turned #2#",
            converts_individual = "#1# into {C:attention}#2#",
            applied = "{C:attention}#1#{} has applied {C:attention}#3#{} to #2#",
            removed_modifier = "{C:attention}#1#{} has removed {C:attention}#3#{} from #2#",
            copies = "{C:attention}#1#{} copied #2#",
            copies_into = "{C:attention}#1#{} turned #3# into #2#",
            money = "{C:attention}#1#{} gave {C:money}$#2#{}",
            money_taken = "{C:attention}#1#{} took {C:money}$#2#{}",
            noped = "{C:attention}#1#{} noped!",
            hand_level_up = "{C:attention}#1#{} leveled up #2#",
            hand_level_down = "{C:attention}#1#{} leveled down #2#",
            leveled_up = "{C:attention}#1#{} leveled up #2#",
            leveled_down = "{C:attention}#1#{} leveled down #2#",
            area_size = "{C:attention}#1#{} size changed: {C:red}#2#{} -> {C:red}#3#{}",
            change_area_size = "{C:attention}#1#{} increased {C:attention}#2#{} size by {C:green}#3#",
            change_area_size_neg = "{C:attention}#1#{} reduced {C:attention}#2#{} size by {C:green}#3#",
            sell = "Sold {C:attention}#1#{} for {C:money}$#2#{}",
            buy = "Bought {C:attention}#1#{} for {C:money}$#2#{}",
            booster_opened = "Opened {C:attention}#1#{} that contains #2#",
            booster_skipped = "Skipped {C:attention}#1#{}",
            win = "Won game!",
            lost = "Lost game!",
            lost_endless = "Lost Endless Mode!",
            tag_applied = "{C:attention}#1#{} applied",
            reroll_boss = "Rerolled boss {C:attention}#1#{} -> {C:attention}#2#{}",
            hand_played = "Played {C:attention}#1#{}\nHand contains: #2#",
            hand_played_as = "Hand evaluated as {C:attention}#1#{}",
            hand_scored =
            "Hand scored: {C:attention}#1#{}\nCurrent score: {C:attention}#2#{} | Score to beat: {C:attention}#3#{}",
            score_to_beat = "Score to beat: {C:attention}#1#{}",
            discarded = "Discarded #1#",
            hand_drawn = "Drawn #1#",
            money_altered = "{C:money}$#1#{} -> {C:money}$#2#{}",
            debuffed_hand = "{C:attention}#1#{} not allowed. Hand did not score",
            selected_card = "{C:attention}#1#{} selected #2#",
            changed_sell_cost = "{C:attention}#1#{}'s sell cost changed {C:red}#2#{} -> {C:red}#3#{}",
            target_changed = "{C:attention}#1#{}'s target changed to #2#",
            saved = "Saved by {C:attention}#1#{}",
            eaten = "{C:attention}#1#{} eaten!",
            extinct = "{C:attention}#1#{} extinct!",
            melted = "{C:attention}#1#{} melted!",
            drank = "{C:attention}#1#{} drank!",
            rental = "Paid {C:money}$#2#{} in rent for {C:attention}#1#",
            perishable = "{C:attention}#1#{} perishes in {C:attention}#2#{}",
            perished = "{C:attention}#1#{} perished!",
            scale = "{C:attention}#1#{} values changed #2# -> #3#",
            scale_by = "{C:attention}#1#{} values changed by #2#",
            reset = "{C:attention}#1#{} values reset!",
            scored = "{C:attention}#1#{} scored #2#",
            scored_other = "{C:attention}#1#{} made {C:attention}#2#{} score #3#",
            scored_gen = "Scored #1#",
            blueprint = "{C:attention}#1#{} copied the ability of {C:attention}#2#{}",
            repetition = "{C:attention}#1#{} retriggered {C:attention}#2#{} {C:attention}#3#{} time(s)",
            added_score = "{C:attention}#1#{} added {C:attention}#2#{} to the total score",
            decreased_score = "{C:attention}#1#{} decreased the total score by {C:attention}#2#{}",
            added_xscore = "{C:attention}#1#{} multiplied the total score by {C:attention}#2#{}",
            added_blind_size = "{C:attention}#1#{} added {C:attention}#2#{} to the Blind's requirements",
            decreased_blind_size = "{C:attention}#1#{} decreased the Blind's requirements by {C:attention}#2#{}",
            added_xblind_size = "{C:attention}#1#{} multiplied the Blind's requirements by {C:attention}#2#{}",
            swap = "{C:attention}Swapped{} {C:chips}Chips{} and {C:mult}Mult{}",
            balance = "{C:attention}Balanced{} {C:chips}Chips{} and {C:mult}Mult{}",
        }
    }
}
