return {
    descriptions = {
        Mod = {
            PlayLog = {
                name = "PlayLog",
                text = {
                    "Añade un registro de acciones al juego",
                    " ",
                    "Ícono hecho por {C:attention}J8-Bit"
                }
            }
        },
    },
    misc = {
        playlog_ui = {
            header = "PLAY LOG",
            select_theme = "SELECCIONA TEMA",
            time_format = "FORMATO DE HORA",
            log_opacity = "OPACIDAD",
            log_types = "TIPOS DE REGISTRO",
            open_log_type_selection = "Abrir selección",
            custom_colours = "PERSONALIZAR COLORES  (clickea para abrir la paleta)",
            colour_panel_bg = "Fondo",
            colour_border = 'Borde / Acento',
            colour_header_text = 'Texto',
            copy = "COPIA",
            copy_ok = "OK",
            copied = "COPIADO",
            log_button = "REG",
            config_button = "CFG",
            back_button = "ATRÁS",
            editing_colour = "EDITANDO: ",
            edit_hex = "clickea para escribir el hex"
        },
        playlog_themes = {
            Gold = "Oro",
            Purple = "Púrpura",
            Green = "Verde",
            Red = "Rojo",
            Blue = "Azul",
            Mono = "Mono"
        },
        playlog_types = {
            hand_played = "Mano Jugada",
            added_blind_size = "Tamaño de ciega cambiado",
            added_score = "Puntaje total cambiado",
            blueprint = "Habilidad copiada",
            score = "Punteo de cartas",
            defeated_blind = "Ciega derrotada",
            buy = "Carta comprada",
            changed_sell_cost = "Valor de venta cambiado",
            copies = "Carta copiada",
            scale = "Valores de la carta cambiados",
            eaten = "Comida expiró",
            perished = "Carta pereció",
            started = "Partida comenzada",
            selected_blind = "Ciega seleccionada",
            booster_skipped = "Paquete omitido",
            starting_shop = "Tienda empezada",
            booster_opened = "Paquete abierto",
            use = "Carta usada",
            perishable = "Conteo de perecedero",
            discarded = "Carta descartada",
            start_ante = "Apuesta inicial cambiada",
            creates = "Carta cambiada",
            added = "Carta añadida a la baraja/ranuras",
            reroll_shop = "Tienda renovada",
            money_altered = "Dinero cambiado",
            start_round = "Ronda empezada",
            selected_card = "Carta fue seleccionada por una habilidad",
            sell = "Carta vendida",
            cash_out = "Cobrar",
            converts_multiple = "Múltiples cartas modificadas",
            reroll_shop_into = "Cartas renovadas en la tienda",
            hand_played_as = "Mano de póker jugada cambia",
            blind_disabled = "Ciega inhabilita",
            area_size = "Tamaño de área cambiado",
            target_changed = "Carta seleccionada cambiada",
            options = "Opciones de partida personalizadas",
            score_to_beat = "Puntaje a vencer",
            hand_drawn = "Mano sacada",
            tag_applied = "Etiqueta aplicada",
            reroll_boss = "Ciega jefe renovada",
            win = "Partida ganada",
            change_area_size = "Carta cambió el tamaño de área",
            resume = "Partida resumida",
            hand_scored = "Mano puntuada",
            applied = "Carta modificada (Edición, Sello, Sticker)",
            ending_shop = "Tienda terminada",
            debuffed_hand = "Mano deshabilitada",
            saved = "Fin del juego prevenido",
            destroys = "Carta destruida",
            reset = "Valores de la carta restablecidos",
            hand_level_up = "Mano de póker subió de nivel",
            added_to_shop = "Carta añadida a la tienda",
            leveled_up = "Carta subió de nivel una mano de póker",
            money = "Carta modificó dinero",
            message = "Registro genérico",
            lost = "Partida perdida",
            swap = "Puntaje intercambiado",
            balance = "Puntaje balanceado",
            rental = "Alquiler pagado",
            removed_modifier = "Modificación removida",
            converts = "Carta modificada (Mejora, Categoría, Palo)",
            skip_blind = "Ciega omitida",
            noped = "Carta dijo ¡no!",
            leveled_down = "Mano de póker bajó de nivel",
        },
        playlog_groups = {
            generic = "Registros genéricos",
            player_actions = "Acciones del jugador",
            effects = "Efectos",
            gamestate = "Estado del juego",
            scoring = "Puntaje"
        },
        playlog = {
            -- Formatting
            separator = "#1#, #2#",
            end_separator = "#1# y #2#",
            rank_of_suit = "#1# de #2#",
            playing_card = "Carta de juego",

            -- Areas
            joker_area = "ranuras de comodín",
            consumable_area = "ranuras de consumibles",
            hand_area = "mano",
            deck_area = "baraja",
            shop_jokers_area = "tienda",
            shop_vouchers_area = "tienda de vouchers",
            shop_boosters_area = "tienda de paquetes",

            -- Others
            all_hands = "todas las manos",
            mult = "#1#{} multi", -- the {} is there as a dirty hack to finish the color formatting :3
            chips = "#1#{} fichas",

            -- Logging
            started = "Partida comenzada en #1#",
            started_challenge = "Partida comenzada del desafío {C:attention}#1#{} en #2#",
            resumed = "Partida resumida",
            mod_options = "{C:attention}#1#{}: #2# habilitado",
            selected_blind = "#1# seleccionada",
            defeated_blind = "#1# derrotada",
            blind_disabled = "#1# deshabilitada",
            skip_blind = "#1# omitida",
            skip_blind_for = "#1# omitida por #2#",
            start_round = "Empezó la {C:attention}ronda #1#{}",
            start_ante = "Empezó la {C:attention}apuesta inicial #1#{}",
            ante_modified = "{C:attention}Apuesta inicial{} cambiada {C:red}#1#{} -> {C:red}#2#{}",
            cash_out = "{C:money}$#1#{} cobrado",
            creates = "{C:attention}#1#{} creó #2#",
            destroys = "{C:attention}#1#{} destruyó #2#",
            used = "{C:attention}#1#{} usado",
            starting_shop = "Ingresó a la {C:attention}tienda{}\nTienda contiene: #1#",
            ending_shop = "Salió de la {C:attention}tienda{}",
            reroll_shop = "Renovó la {C:attention}tienda{} por {C:money}$#1#{} a #2#",
            reroll_shop_into = "Renovó a: #1#",
            added = "{C:attention}#1#{} añadido",
            added_to = "{C:attention}#1#{} añadido a {C:attention}#2#",
            added_to_shop = "{C:attention}#1#{} añadió {C:attention}#2#{} a la {C:attention}tienda{}",
            converts = "{C:attention}#1#{} convirtió #2# en {C:attention}#3#",
            converts_multiple = "{C:attention}#1#{} convirtió #2#",
            converts_individual = "#1# en {C:attention}#2#",
            applied = "{C:attention}#1#{} aplicó {C:attention}#3#{} a #2#",
            removed_modifier = "{C:attention}#1#{} removió {C:attention}#3#{} de #2#",
            copies = "{C:attention}#1#{} copió #2#",
            copies_into = "{C:attention}#1#{} convirtió #3# en #2#",
            money = "{C:attention}#1#{} dio {C:money}$#2#{}",
            money_taken = "{C:attention}#1#{} tomó {C:money}$#2#{}",
            noped = "{C:attention}#1#{} dijo ¡no!",
            hand_level_up = "{C:attention}#1#{} subió de nivel en #2#",
            hand_level_down = "{C:attention}#1#{} bajó de nivel en #2#",
            leveled_up = "{C:attention}#1#{} subió de nivel #2#",
            leveled_down = "{C:attention}#1#{} bajó de nivel #2#",
            area_size = "Cambio de tamaño de {C:attention}#1#{}: {C:red}#2#{} -> {C:red}#3#{}",
            change_area_size = "{C:attention}#1#{} aumentó el tamaño de {C:attention}#2#{} en {C:green}#3#",
            change_area_size_neg = "{C:attention}#1#{} redujo el tamaño de {C:attention}#2#{} en {C:green}#3#",
            sell = "Vendió {C:attention}#1#{} por {C:money}$#2#{}",
            buy = "Compró {C:attention}#1#{} por {C:money}$#2#{}",
            booster_opened = "Abrió {C:attention}#1#{} que contiene #2#",
            booster_skipped = "{C:attention}#1#{} omitido",
            win = "¡Ganó la partida!",
            lost = "¡Perdió la partida!",
            lost_endless = "¡Perdió en el modo infinito!",
            tag_applied = "{C:attention}#1#{} aplicó",
            reroll_boss = "Renovó ciega jefe {C:attention}#1#{} -> {C:attention}#2#{}",
            hand_played = "Jugó {C:attention}#1#{}\nMano contiene: #2#",
            hand_played_as = "Mano de póker evaluada como {C:attention}#1#{}",
            hand_scored =
            "Mano puntuó: {C:attention}#1#{}\nPuntaje actual: {C:attention}#2#{} | Puntaje a vencer: {C:attention}#3#{}",
            score_to_beat = "Puntaje a vencer: {C:attention}#1#{}",
            discarded = "#1# descartado",
            hand_drawn = "#1# sacado",
            money_altered = "{C:money}$#1#{} -> {C:money}$#2#{}",
            debuffed_hand = "{C:attention}#1#{} no está permitido. La mano no puntuó",
            selected_card = "{C:attention}#1#{} seleccionó #2#",
            changed_sell_cost = "Valor de venta de {C:attention}#1#{} cambió {C:red}#2#{} -> {C:red}#3#{}",
            target_changed = "Objetivo de {C:attention}#1#{} cambió a #2#",
            saved = "Salvado por {C:attention}#1#{}",
            eaten = "¡{C:attention}#1#{} se devoró!",
            extinct = "¡{C:attention}#1#{} se extinguió!",
            melted = "¡{C:attention}#1#{} se derritió!",
            drank = "¡{C:attention}#1#{} consumido!",
            rental = "{C:money}$#2#{} pagado de alquiler a {C:attention}#1#",
            perishable = "{C:attention}#1#{} perece en {C:attention}#2#{}",
            perished = "¡{C:attention}#1#{} perecido!",
            scale = "Valores de {C:attention}#1#{} cambiaron #2# -> #3#",
            scale_by = "Valores de {C:attention}#1#{} cambiaron en #2#",
            reset = "¡Los valores de {C:attention}#1#{} se han restablecidos!",
            scored = "{C:attention}#1#{} puntuó #2#",
            scored_other = "{C:attention}#1#{} hizo que {C:attention}#2#{} puntue #3#",
            scored_gen = "Puntuó #1#",
            blueprint = "{C:attention}#1#{} copió la habilidad de {C:attention}#2#{}",
            repetition = "{C:attention}#1#{} reactivó {C:attention}#2#{} {C:attention}#3#{} veces",
            added_score = "{C:attention}#1#{} añadió {C:attention}#2#{} al puntaje total",
            decreased_score = "{C:attention}#1#{} redujo el puntaje total en {C:attention}#2#{}",
            added_xscore = "{C:attention}#1#{} multiplicó el puntaje total por {C:attention}#2#{}",
            added_blind_size = "{C:attention}#1#{} añadió {C:attention}#2#{} al puntaje requerido",
            decreased_blind_size = "{C:attention}#1#{} redujo el puntaje requerido en {C:attention}#2#{}",
            added_xblind_size = "{C:attention}#1#{} multiplicó el puntaje requerido por {C:attention}#2#{}",
            swap = "{C:attention}Intercambió{} {C:chips}fichas{} y {C:mult}multi{}",
            balance = "{C:attention}Balanceó{} {C:chips}fichas{} y {C:mult}multi{}",
        }
    }
}
