[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "for k, v in pairs(self.I.CARD) do"
position = 'before'
match_indent = true
payload = '''
if PlayLog then PlayLog.draw() end
'''

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "for _, v in ipairs(info_queue) do"
position = 'before'
match_indent = true
payload = '''
if PlayLog and PlayLog.no_info_queue then info_queue = {} end
'''

[[patches]]
[patches.pattern]
target = "back.lua"
pattern = '''
return
{n=G.UIT.ROOT, config={align = "cm", minw = min_dims*5, minh = min_dims*2.5, id = self.name, colour = G.C.CLEAR}, nodes={
    challenge.id and UIBox_button({button = 'deck_view_challenge', label = {localize(challenge.id, 'challenge_names')},  minw = 2.2, minh = 1, scale = 0.6, id = challenge})
    or desc_from_rows(loc_nodes, true, min_dims*5)
}}
'''
position = 'before'
match_indent = true
payload = '''
if PlayLog and PlayLog.back_generate_ui then return loc_nodes end
'''
