[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# G.FUNCS.cash_out
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "ease_dollars(G.GAME.current_round.dollars)"
position = 'before'
match_indent = true
payload = '''
PlayLog.log{ type = "cash_out", amount = G.GAME.current_round.dollars }
'''

# G.FUNCS.skip_blind
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "add_tag(_tag.config.ref_table)"
position = 'after'
match_indent = true
payload = '''
PlayLog.log{ type = "skip_blind", tag = _tag.config.ref_table.key, blind = G.GAME.round_resets.blind_choices[G.GAME.blind_on_deck] }
'''

# Lost game
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if G.GAME.round_resets.ante <= G.GAME.win_ante then --Only add Jimbo to say a quip if the game over happens when the run is lost"
position = 'before'
match_indent = true
payload = '''
PlayLog.log{ type = "lost", endless = G.GAME.round_resets.ante > G.GAME.win_ante }
'''

# Rental
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "ease_dollars(-G.GAME.rental_rate)"
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        PlayLog.log{ type = "rental", card = self, amount = G.GAME.rental_rate }
        return true
    end
}))
'''

# Perishable
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.area == G.jokers then self:remove_from_deck(true) end"
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        PlayLog.log{ type = "perished", card = self }
        return true
    end
}))
'''

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "self.ability.perish_tally = self.ability.perish_tally - 1"
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        PlayLog.log{ type = "perishable", card = self, amount = self.ability.perish_tally }
        return true
    end
}))
'''

# Scaling
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "if next(scaling_message) and not args.no_message then"
position = 'after'
match_indent = true
payload = '''
    G.E_MANAGER:add_event(Event({
        func = function()
            PlayLog.log{ type = "scale", card = card, previous = initial, current = args.ref_table[args.ref_value], amount = scalar_value, effect = args.ref_value }
            return true
        end
    }))
'''
