[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Blue Seal
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
local card = create_card(card_type,G.consumeables, nil, nil, nil, nil, _planet, 'blusl')
card:add_to_deck()
G.consumeables:emplace(card)
'''
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        PlayLog.log{ type = "creates", card = self.seal, created = { card } }
        return true
    end
}))
'''

# Purple Seal, 8 Ball
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''
local card = create_card('Tarot',G.consumeables, nil, nil, nil, nil, nil, '8ba')
card:add_to_deck()
G.consumeables:emplace(card)
'''
position = 'after'
match_indent = true
payload = '''
G.E_MANAGER:add_event(Event({
    func = function()
        PlayLog.log{ type = "creates", card = self.seal or self, created = { card } }
        return true
    end
}))
'''
